GET http://localhost:8080/api/projects/6886794fd17a0e7c6698ce25
### Popula banco
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Claudia",
  "email": "claudia@email.com",
  "password": "123456",
  "role": "ADMIN",
  "avatarUrl": "https://imagem.com/avatar.jpg"
}



### Criar nova Task vinculada a um Projeto
POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGF1ZGlhQGVtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJDbGF1ZGlhIiwiaWF0IjoxNzU2MDU5MjMyLCJleHAiOjE3NTYxNDU2MzJ9.BnUWOrVy-nlVboGcF15SIf1wpEJ2yCqcdCbEVTJslqA

{
  "title": "Criar layout do Kanban",
  "assignee": "everson",
  "projectId": "INSIRA_ID_DO_PROJETO_AQUI"
}



### Autenticação
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "claudia@email.com",
  "password": "123456"
}

### Autenticação
POST http://localhost:8080/api/dev/users
Content-Type: application/json

{
  "name": "Everson",
  "email": "everson@email.com",
  "password": "123456",
  "role": "ADMIN",
  "avatarUrl": null
}


